---
- hosts: all
  become: yes
  vars:
   - password: '$6$bn/p9Nwrg7Ot1CnW$OvVoNtgvZcVFuYwR/4tyMoajArQLMHXsXO.xxxxxxxxxxxxxx'
  tasks:
   - name: Change root password
     user: name=root update_password=always password={{password}}
...
